env:
  global:
    - HUGO_VERSION="0.58.2"
  matrix:
    - YOUR_ENCRYPTED_VARIABLE

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
  - sudo apt-get update && sudo apt-get install npm
  - npm install postcss-cli
  - mv hugo ~/bin/

script:
  - HUGO_ENV="production" hugo --gc --minify

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  repo: mixxit/solinia.github.io
  target-branch: master
  verbose: true
  on:
    branch: master
