name: Solinia Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        HUGO_VERSION: "0.58.2"
      run: |
        wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        tar xf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        sudo apt-get update && sudo apt-get install nodejs-dev node-gyp libssl1.0-dev && sudo apt-get install npm
        npm install postcss-cli
        mkdir -p ~/bin && mv hugo ~/bin/
        HUGO_ENV="production" ~/bin/hugo --gc --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.CI_DEPLOY_KEY }}
        external_repository: mixxit/solinia.github.io
        publish_branch: master
        publish_dir: ./public
        keep_files: true
